resources:
- ../../base

namespace: dev

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: mywebapp

configMapGenerator:
- name: mykustom-map
  behavior: replace
  envs:
  - config.properties
