resources: 
- deployment.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app: mykustomapp

commonAnnotations:
  app: mykustom-annontations

namePrefix: "kustom-"

nameSuffix: "-v1"

configMapGenerator:
- name: mykustom-map
  behavior: replace
  envs:
    - config.properties
